# Generated by Django 2.1.7 on 2019-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competition', '0002_auto_20190330_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='contestants',
            field=models.ManyToManyField(blank=True, to='competition.Contestant'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='answers',
            field=models.ManyToManyField(blank=True, default=[], to='competition.Answer'),
        ),
    ]
