# Generated by Django 2.1.7 on 2019-03-30 20:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_question_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.CharField(max_length=10),
        ),
    ]
