# Generated by Django 2.1.7 on 2019-03-31 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competition', '0005_auto_20190330_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='competition.Contestant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestant',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='competition.Competition'),
            preserve_default=False,
        ),
    ]
