# Generated by Django 2.1.7 on 2019-04-01 18:30

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competition', '0006_auto_20190331_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tag',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
