# Generated by Django 2.1.7 on 2019-04-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competition', '0007_auto_20190401_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='participant',
            new_name='contestant',
        ),
        migrations.RenameField(
            model_name='contestant',
            old_name='race',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='race',
            new_name='competition',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='contestants',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='answers',
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
