# Generated by Django 2.1.7 on 2019-04-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competition', '0009_auto_20190404_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='given_answer',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
